### ISSUE TITLE
EpiExpert submission feedback.

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-german-forecasts#11]
I just submitted from my IPad as no laptop with me. Everything went okay but had a couple of points of frustration. These are all just notes and not suggested changes. 

* plotly plots do not work with touch screens and are in fact a hindrance (as they randomly zoom etc + compress strangely on an iPad screen). I found myself wishing for switch to make the plots static. 

* really struggled to hit the domain experience check box using a touch screen this may have something to do with the pop ups. 

* popups. As we discussed these are really helpful when you don’t know what you are doing but if you do they put on lot of noise on the screen. On iPad the popups really got in the way and seemed to make it hard to fill in value etc. Potentially having them be optionally switched off would help? 

Otherwise all good and certainly doable from an iPad. Not sure if this is already present but perhaps having a note in the instructions saying designed for a mouse and keyboard might be all it needs. Excited to see the leaderboard (if you have this for last week I am keen to see but please email to my personal email etc as no slack Or work email)

**Comment by nikosbosse** [comment]
Thanks for the feedback!
I'll look into these things. I'm not sure tipify has any functionality such that I could globally switch it off. The only thing I can imagine ad hoc (but need to think more about it) is to make an if-statement before every single button and field which kind of seems like a nightmare...

**Comment by sbfnk** [comment]
I had the same popup issue for the domain expertise on a laptop.

**Comment by seabbs** [comment]
You could wrap it in another function which has the switch. 

So something along the lines of the following.

```
controlled_tipfy(..., show_tip = TRUE) {
if (show_tip) { 
 tipify(...)
 }
}

**Comment by nikosbosse** [comment]
I think the problem with that solution is that tipify is only used in the ui() call, not in the server() call (I haven't actually tried it)
What I have tried and what works is the tooltip from shinyBS (https://ebailey78.github.io/shinyBS/docs/Tooltips_and_Popovers.html#removeTooltip)

**Comment by seabbs** [comment]
ah yes makes sense. Nice sounds sensible.
