### ISSUE TITLE
EpiNow2 update 19/10/2020

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/covid-german-forecasts#9]
I am unable to update the forecast tomorrow/Tuesday. 

If you would like to submit an `EpiNow2` forecast this can be done by updating all dependencies as listed in the `DESCRIPTION` and then running `bash rt-forecast/update.sh`.

Runtime should be 20 ~ 30 minutes on a 4 core computer. If your unable to run this update please close this issue.

**Comment by nikosbosse** [comment]
Will do! Thanks

**Comment by nikosbosse** [comment]
I'm having some trouble with the forecast. These are the error messages I get: 
![image](https://user-images.githubusercontent.com/37978797/96489907-619fc680-1240-11eb-9268-81515a478841.png)
![image](https://user-images.githubusercontent.com/37978797/96489964-74b29680-1240-11eb-9ec1-cb0abd775bda.png)

I'm reaching some time limit (also the progressr bar doesn't update), but I don't know where to look. Do you have any ad hoc thoughts?

**Comment by seabbs** [comment]
Annoying. Do the expanded logs have any more detail (i.e in the logs folder?)

**Comment by nikosbosse** [comment]
I'll check again later or tomorrow. Just reran the thing and now it maybe kind of worked? 
![image](https://user-images.githubusercontent.com/37978797/96497232-acbed700-124a-11eb-9763-72cbbafd90fd.png)
still some error, but I think at least it produced something
I'll keep you posted :)

**Comment by seabbs** [comment]
borrowed a computer - hot fixing now. Issue flagged and fixed by @medewitt

**Comment by nikosbosse** [comment]
hmm. Apparently not. There is some output, but formatting did not work
![image](https://user-images.githubusercontent.com/37978797/96497406-ec85be80-124a-11eb-97f2-f9cdf014eea6.png)

**Comment by seabbs** [comment]
For a note there are written logs with more detail in the logs folder.

**Comment by nikosbosse** [comment]
Going through the logs right now. 

for the cases: 
INFO [2020-10-19 18:58:30] Runtime error in Germany : $ operator is invalid for atomic vectors - 
INFO [2020-10-19 18:58:30] Runtime error in Poland : $ operator is invalid for atomic vectors - 

INFO [2020-10-19 18:27:56] Reporting estimates using data up to: 2020-10-19
INFO [2020-10-19 18:27:56] Saving estimates to : /mnt/data/Google Drive/Uni/PhD/covid-german-forecasts/rt-forecast/data/samples/cases
INFO [2020-10-19 18:27:56] Producing estimates for: Germany, Poland
INFO [2020-10-19 18:27:56] Regions excluded: none
INFO [2020-10-19 18:27:56] Showing progress using progressr. Modify this behaviour using progressr::handlers.
INFO [2020-10-19 18:58:30] Completed regional estimates
INFO [2020-10-19 18:58:30] Regions with estimates: 0
INFO [2020-10-19 18:58:30] Regions with runtime errors: 2
INFO [2020-10-19 18:58:30] Saving timings information to : /mnt/data/Google Drive/Uni/PhD/covid-german-forecasts/rt-forecast/data/samples/cases
INFO [2020-10-19 19:11:57] Reporting estimates using data up to: 2020-10-19
INFO [2020-10-19 19:11:57] Saving estimates to : /mnt/data/Google Drive/Uni/PhD/covid-german-forecasts/rt-forecast/data/samples/cases
INFO [2020-10-19 19:11:57] Producing estimates for: Germany, Poland
INFO [2020-10-19 19:11:57] Regions excluded: none
INFO [2020-10-19 19:11:57] Showing progress using progressr. Modify this behaviour using progressr::handlers.
INFO [2020-10-19 19:34:49] Completed regional estimates
INFO [2020-10-19 19:34:49] Regions with estimates: 2
INFO [2020-10-19 19:34:49] Regions with runtime errors: 0
INFO [2020-10-19 19:34:49] Producing summary
INFO [2020-10-19 19:34:49] Saving summary to : /mnt/data/Google Drive/Uni/PhD/covid-german-forecasts/rt-forecast/data/summary/cases/2020-10-19
INFO [2020-10-19 19:34:49] Errors caught whilst generating summary statistics: 
INFO [2020-10-19 19:34:49] Error: `device` must be NULL, a string or a function.

INFO [2020-10-19 19:34:49] Saving timings information to : /mnt/data/Google Drive/Uni/PhD/covid-german-forecasts/rt-forecast/data/samples/cases

for the deaths: 
INFO [2020-10-19 19:47:55] Reporting estimates using data up to: 2020-10-19
INFO [2020-10-19 19:47:55] Saving estimates to : /mnt/data/Google Drive/Uni/PhD/covid-german-forecasts/rt-forecast/data/samples/deaths
INFO [2020-10-19 19:47:55] Producing estimates for: Germany, Poland
INFO [2020-10-19 19:47:55] Regions excluded: none
INFO [2020-10-19 19:47:55] Showing progress using progressr. Modify this behaviour using progressr::handlers.
INFO [2020-10-19 20:02:26] Completed regional estimates
INFO [2020-10-19 20:02:26] Regions with estimates: 2
INFO [2020-10-19 20:02:26] Regions with runtime errors: 0
INFO [2020-10-19 20:02:26] Producing summary
INFO [2020-10-19 20:02:26] Saving summary to : /mnt/data/Google Drive/Uni/PhD/covid-german-forecasts/rt-forecast/data/summary/deaths/2020-10-19
INFO [2020-10-19 20:02:26] Errors caught whilst generating summary statistics: 
INFO [2020-10-19 20:02:26] Error: `device` must be NULL, a string or a function.

INFO [2020-10-19 20:02:26] Saving timings information to : /mnt/data/Google Drive/Uni/PhD/covid-german-forecasts/rt-forecast/data/samples/deaths

**Comment by nikosbosse** [comment]
shall I push any of the things I did so far?

**Comment by sbfnk** [comment]
Isn't the problem that `ggsave` doesn't receive the `plot` object [here](https://github.com/epiforecasts/EpiNow2/blob/baca6e4f41643ab1f60bb4ce21415e0e629b937d/R/summarise.R#L246)?

**Comment by seabbs** [comment]
Did you make any changes? If all just errors probably not! :)

There should be lower level logs in the other two folders - thanks for checking. As I am here will try the hot fix out to see if it fixes the issue s.

**Comment by nikosbosse** [comment]
just pushed everything to a new branch - maybe that gives you more information

**Comment by seabbs** [comment]
@sbfnk the summary is failing I think because all the estimates are falling over so there isn't anything to summarise. @medewitt has flagged the issue (epiforecasts/EpiNow2#129) and provided a fix. So just testing on the german data and will see if that resolves the summarise issues or not.

**Comment by sbfnk** [comment]
Happy to believe you but doesn't this suggest that estimates are succeeding? 

INFO [2020-10-19 19:34:49] Regions with estimates: 2
INFO [2020-10-19 19:34:49] Regions with runtime errors: 0

In my case the csv summaries are generated just no plots - @nikosbosse are there csv files in the summary directory?

**Comment by seabbs** [comment]
Agree - added hot fix.

**Comment by seabbs** [comment]
Closed in #12 - @nikosbosse please review and submit if possible along with the `EpiExpert` forecast.

**Comment by nikosbosse** [comment]
will do! thanks for the fixing
